###
GET http://localhost:5000/initialize-database

###
GET http://localhost:5000/products/transactions?month=January&search=backpack

###
GET http://localhost:5000/products/statistics?month=December 

###
GET http://localhost:5000/products/barChart?month=December

###
GET http://localhost:5000/products/pieChart?month=November

###
GET http://localhost:5000/products/combinedData?month=December

###
GET http://localhost:5000/products/transactions/1